### PR TITLE
Improved README examples.

### PR DESCRIPTION
**Pull request by colshacol**
First, I want to say that this is an awesome tool you are creating. It is a tool that **absolutely** needs to exist, but it is a big task to take on so nobody has stepped up! I have been working on a canvas based app for a few months now and it has not been fun working with `react-konva`. (Which is basically the only option for React 16 and canvas.)

For the past month I have been considering creating this library myself, but knew it would be a lot to do by myself so I hadn't started yet. I am glad you took action. I'd like to support you in development of `revas`, as I think it could be the React canvas library that the world needs. 🙏 

---

In README.md, I was confused at first by `createCanvas()` and how exactly to use `render`, so after I figured it out I decided it would be good to make the example a little bit easier to understand and also to provide a second example showing how to use `render` if the target canvas is rendered in the React tree. 👍 These changes are represented in this PR.

I am open to discuss rewording the description I added to the README, and to refactoring the example code I added if it is not to your liking. Just let me know what you think!

### CODE REVIEW

**Comment by colshacol** [comment]
Also, it looks like my `prettier.formatOnSave` got ahold of the README and tidied it up a wee bit. Hope that's okay.

**Comment by pinqy520** [comment]
@colshacol  
I'm very very happy to receive this PR, you saved my bad English, and, indeed, there is still a lot of work to do, and I really don't have much time in the documentation and examples, and your example helps a lot.

In my [previous example](https://github.com/pinqy520/revas/blob/master/src/develop/App.tsx), the code about `createCanvas` is [here](https://github.com/pinqy520/revas/blob/master/src/develop/createCanvas.ts). and i think, in your example, there is no need to use `react-dom`. You can just create a canvas with `document.createElement ('canvas')`, and you also need to add support for high dpi screens, like [this](https://github.com/pinqy520/revas/blob/master/src/develop/createCanvas.ts#L2-L9)

In addition, I don’t know if `codesandbox` preview supports the TouchEvent. Currently, Revas only supports TouchEvent for interaction.

I just started writing REVAS last Friday, and there is still a lot of work to do, such as:

- More components such as ListView, FlatList
- iOS and Android Canvas support
- Off-screen rendering
- Documentation, website and more examples

and If you are interested, we can do this together

Now. It's very late in China. I have to go to bed. I will merge this PR in the morning after i get up. and Thank you again for this PR

**Review by pinqy520 — COMMENTED** [review]
In [my previous example](https://github.com/pinqy520/revas/blob/master/src/develop/App.tsx), the code about `createCanvas` is [here](https://github.com/pinqy520/revas/blob/master/src/develop/createCanvas.ts). and i think, in your example, there is no need to use `react-dom`. You can just create a canvas with `document.createElement('canvas')`, and you also need to add support for high dpi screens, like [this](https://github.com/pinqy520/revas/blob/master/src/develop/createCanvas.ts#L2-L9)

**Comment by colshacol** [comment]
I see now. I can make those changes.

I think the react-DOM example may be necessary to have available somewhere so it is clear how you might approach using revas on a canvas created from a react component. I think the majority of canvas apps are not built 100% in canvas. They are complex UIs rendered with React and the canvas element they developer may need to control is going to be found somewhere nested in the component tree.

Thoughts?

**Comment by pinqy520** [comment]
@colshacol  i think you are right~

Do you have any other code to submit? I am ready to merge

**Pull request merged**
